version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.3.4
    ports:
      - '9200:9200'
    networks:
      - monitoring_net
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    networks:
      - monitoring_net
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    depends_on:
      - elasticsearch
  dockerbeats:
    image: ladicle/alpin-dockerbeat:1.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring_net
    depends_on:
      - elasticsearch
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/log:/fluentd/log
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
    networks:
      - monitoring_net
    depends_on:
      - elasticsearch
networks:
  monitoring_net:
    driver: bridge
